apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hwala-core.fullname" . }}-config
  labels:
    {{- include "hwala-core.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.api.env.NODE_ENV | default "production" | quote }}
  PORT: {{ .Values.api.env.PORT | default "3000" | quote }}
  REDIS_HOST: "{{ include "hwala-core.fullname" . }}-redis"
  REDIS_PORT: "6379"
  THROTTLE_TTL: {{ .Values.config.throttleTtl | quote }}
  THROTTLE_LIMIT: {{ .Values.config.throttleLimit | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
