apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hwala-core.fullname" . }}-api-policy
  labels:
    {{- include "hwala-core.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hwala-core.apiSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "hwala-core.postgresSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              {{- include "hwala-core.redisSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hwala-core.fullname" . }}-db-policy
  labels:
    {{- include "hwala-core.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hwala-core.postgresSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "hwala-core.apiSelectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "hwala-core.workerSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
