{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hwala-core.fullname" . }}-api-pdb
  labels:
    {{- include "hwala-core.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "hwala-core.apiSelectorLabels" . | nindent 6 }}
{{- end }}
