apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hwala-core.fullname" . }}-secrets
  labels:
    {{- include "hwala-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "hwala-core.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}?schema=public"
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
